[package]
name = "avelune-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Command-line tools for the experimental Avelune audiovisual codec family"
publish = false

[[bin]]
name = "avelune"
path = "src/main.rs"
doc = false

[dependencies]
avelune-container-v1 = { path = "../../crates/avelune-container-v1" }
avelune-video-v1 = { path = "../../crates/avelune-video-v1" }
avelune-audio-v1 = { path = "../../crates/avelune-audio-v1" }
avelune-video-ref-v1 = { path = "../../crates/avelune-video-ref-v1" }
clap = { version = "4.6.6", features = ["derive", "color", "help", "usage", "error-context", "suggestions"] }
clap_complete = "4.6.9"

[lints]
workspace = true
