const $=id=>document.getElementById(id); const td=new TextDecoder();
function show(id,value){let node=$(id);if(node)node.textContent=value}
function streamFormat(stream){let codec=stream.codec===1?(stream.kind===1?'ALV1':'ALA1'):`codec ${stream.codec}`;return stream.kind===1?`${codec} · ${stream.p0} × ${stream.p1}`:`${codec} · ${stream.p0} Hz · ${stream.p1} ch`}
function u16(v,o){return v.getUint16(o,true)} function u32(v,o){return v.getUint32(o,true)} function u64(v,o){return Number(v.getBigUint64(o,true))}
const crcTable=(()=>{let t=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0x82f63b78:0);t[i]=c>>>0}return t})();
function crc32c(a){let c=0xffffffff;for(const b of a)c=(c>>>8)^crcTable[(c^b)&255];return (~c)>>>0}
async function range(url,a,b){show('playback-range',`${a}–${b}`);let r=await fetch(url,{headers:{Range:`bytes=${a}-${b}`},cache:'no-store'});if(r.status!==206)throw Error(`server must support HTTP Range; got ${r.status} for ${a}-${b}`);let z=new Uint8Array(await r.arrayBuffer());if(z.length!==b-a+1)throw Error('short range');return z}
async function index(url){let h=await range(url,0,31),v=new DataView(h.buffer);if(td.decode(h.slice(0,7))!=='AVELUNE')throw Error('not Avelune');if(u16(v,8)!==1)throw Error('not v1');if(crc32c(h.slice(0,28))!==u32(v,28))throw Error('header CRC');let fl=u32(v,24);let f=await range(url,32,31+fl),fv=new DataView(f.buffer,f.byteOffset,f.byteLength);if(td.decode(f.slice(0,4))!=='AVFR')throw Error('front magic');if(crc32c(f.slice(0,-4))!==u32(fv,f.length-4))throw Error('front CRC');let sc=u16(fv,6),ec=u32(fv,8),p=12,streams=[];for(let i=0;i<sc;i++){streams.push({id:u16(fv,p),kind:f[p+2],codec:f[p+3],timescale:u32(fv,p+4),p0:u32(fv,p+8),p1:u32(fv,p+12),flags:u32(fv,p+16),meta0:u32(fv,p+20)});p+=24}let epochs=[];for(let i=0;i<ec;i++){epochs.push({id:u32(fv,p),duration:u32(fv,p+4),pts:u64(fv,p+8),offset:u64(fv,p+16),len:u64(fv,p+24)});p+=32}return{head:h,front:f,streams,epochs}}
function packets(b){let out=[],p=0;while(p<b.length){if(p+28>b.length)throw Error('truncated packet header');if(String.fromCharCode(...b.slice(p,p+4))!=='AVPK')throw Error(`packet magic @${p}`);let v=new DataView(b.buffer,b.byteOffset+p,28);if(crc32c(b.slice(p,p+24))!==u32(v,24))throw Error('packet header CRC');let len=u32(v,20),end=p+28+len+4;if(end>b.length)throw Error('truncated payload');let payload=b.slice(p+28,p+28+len);let pv=new DataView(b.buffer,b.byteOffset+p+28+len,4);if(crc32c(payload)!==u32(pv,0))throw Error('payload CRC');out.push({kind:b[p+4],stream:u16(v,6),pts:u64(v,8),duration:u32(v,16),payload});p=end}return out}
let wasm,ex,idx,currentUrl,renderer,ctxAudio,nextAudio=0,playToken=0;
async function wasmInit(){if(wasm)return;let r=await fetch('avelune.wasm');let x=await WebAssembly.instantiateStreaming(r,{});wasm=x.instance;ex=wasm.exports}
function input(payload){let p=ex.avelune_input_resize(payload.length);new Uint8Array(ex.memory.buffer,p,payload.length).set(payload)}
function decodeVideo(payload){input(payload);if(ex.avelune_decode_video_input(payload.length)!==0)throw Error(`video decode ${ex.avelune_last_error()}`);let w=ex.avelune_video_width(),h=ex.avelune_video_height(),yn=ex.avelune_video_y_len(),uvn=ex.avelune_video_uv_len(),yp=ex.avelune_video_y_ptr(),up=ex.avelune_video_u_ptr(),vp=ex.avelune_video_v_ptr(),yuv=new Uint8Array(yn+2*uvn);yuv.set(new Uint8Array(ex.memory.buffer,yp,yn),0);yuv.set(new Uint8Array(ex.memory.buffer,up,uvn),yn);yuv.set(new Uint8Array(ex.memory.buffer,vp,uvn),yn+uvn);show('format-dimensions',`${w} × ${h}`);return{w,h,yuv}}
function decodeAudio(payload){input(payload);if(ex.avelune_decode_audio_input(payload.length)!==0)throw Error(`audio decode ${ex.avelune_last_error()}`);let rate=ex.avelune_audio_rate(),ch=ex.avelune_audio_channels(),n=ex.avelune_audio_len_samples(),p=ex.avelune_audio_ptr();return{rate,ch,pcm:new Int16Array(ex.memory.buffer,p,n).slice()}}
function colorParams(meta0){
  let matrix=meta0&15,full=!!(meta0&(1<<12));
  // Coefficients map normalized Y,U,V to normalized RGB. Unspecified falls
  // back to BT.709; the stream metadata remains visible in inspect/status.
  let c;
  if(matrix===1)c=full?[1,0,1.402,-.344136,-.714136,1.772]:[1.164,16/255,1.596,-.392,-.813,2.017];
  else if(matrix===3)c=full?[1,0,1.4746,-.16455,-.57135,1.8814]:[1.164,16/255,1.6787,-.1873,-.6504,2.1418];
  else c=full?[1,0,1.5748,-.187324,-.468124,1.8556]:[1.164,16/255,1.793,-.213,-.533,2.112];
  return c;
}
class CanvasRenderer{constructor(c,meta0){this.c=c;this.x=c.getContext('2d');this.k=colorParams(meta0)}render(f){let{w,h,yuv}=f,[ys,yo,rv,gu,gv,bu]=this.k;this.c.width=w;this.c.height=h;let im=this.x.createImageData(w,h),Y=yuv,U=yuv.subarray(w*h,w*h+w*h/4),V=yuv.subarray(w*h+w*h/4);for(let j=0,k=0;j<h;j++)for(let i=0;i<w;i++,k++){let y=Y[k]/255,u=U[(j>>1)*(w>>1)+(i>>1)]/255-.5,v=V[(j>>1)*(w>>1)+(i>>1)]/255-.5,yy=ys*(y-yo),r=(yy+rv*v)*255,g=(yy+gu*u+gv*v)*255,b=(yy+bu*u)*255,q=k*4;im.data[q]=Math.max(0,Math.min(255,r));im.data[q+1]=Math.max(0,Math.min(255,g));im.data[q+2]=Math.max(0,Math.min(255,b));im.data[q+3]=255}this.x.putImageData(im,0,0)}}
class WebGPURenderer{static async make(c,meta0){if(!navigator.gpu)return null;let ad=await navigator.gpu.requestAdapter();if(!ad)return null;let d=await ad.requestDevice(),ctx=c.getContext('webgpu'),fmt=navigator.gpu.getPreferredCanvasFormat();ctx.configure({device:d,format:fmt,alphaMode:'opaque'});let code=`@group(0) @binding(0) var ys:texture_2d<f32>;@group(0) @binding(1) var us:texture_2d<f32>;@group(0) @binding(2) var vs:texture_2d<f32>;@group(0) @binding(3) var sm:sampler;struct K{a:vec4f,b:vec4f};@group(0) @binding(4) var<uniform> k:K;struct O{@builtin(position)p:vec4f,@location(0)uv:vec2f};@vertex fn v(@builtin(vertex_index)i:u32)->O{var p=array<vec2f,3>(vec2f(-1.,-1.),vec2f(3.,-1.),vec2f(-1.,3.));var o:O;o.p=vec4f(p[i],0.,1.);o.uv=vec2f((p[i].x+1.)*.5,1.-(p[i].y+1.)*.5);return o}@fragment fn f(i:O)->@location(0) vec4f{let y=k.a.x*(textureSampleLevel(ys,sm,i.uv,0.).r-k.a.y);let u=textureSampleLevel(us,sm,i.uv,0.).r-.5;let vv=textureSampleLevel(vs,sm,i.uv,0.).r-.5;return vec4f(y+k.a.z*vv,y+k.a.w*u+k.b.x*vv,y+k.b.y*u,1.)}`;let mod=d.createShaderModule({code}),pipe=d.createRenderPipeline({layout:'auto',vertex:{module:mod,entryPoint:'v'},fragment:{module:mod,entryPoint:'f',targets:[{format:fmt}]},primitive:{topology:'triangle-list'}}),sm=d.createSampler({magFilter:'linear',minFilter:'linear'});let vals=colorParams(meta0),ub=d.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});d.queue.writeBuffer(ub,0,new Float32Array([vals[0],vals[1],vals[2],vals[3],vals[4],vals[5],0,0]));return new WebGPURenderer(c,d,ctx,pipe,sm,ub)}constructor(c,d,x,p,s,u){Object.assign(this,{c,d,x,p,s,u})}tex(w,h,data){let t=this.d.createTexture({size:[w,h],format:'r8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});this.d.queue.writeTexture({texture:t},data,{bytesPerRow:w,rowsPerImage:h},{width:w,height:h});return t}render(f){let{w,h,yuv}=f;this.c.width=w;this.c.height=h;let n=w*h,c=n/4,Y=this.tex(w,h,yuv.subarray(0,n)),U=this.tex(w/2,h/2,yuv.subarray(n,n+c)),V=this.tex(w/2,h/2,yuv.subarray(n+c));let bg=this.d.createBindGroup({layout:this.p.getBindGroupLayout(0),entries:[{binding:0,resource:Y.createView()},{binding:1,resource:U.createView()},{binding:2,resource:V.createView()},{binding:3,resource:this.s},{binding:4,resource:{buffer:this.u}}]});let enc=this.d.createCommandEncoder(),pass=enc.beginRenderPass({colorAttachments:[{view:this.x.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:1}}]});pass.setPipeline(this.p);pass.setBindGroup(0,bg);pass.draw(3);pass.end();this.d.queue.submit([enc.finish()])}}
async function chooseRenderer(meta0){try{let r=await WebGPURenderer.make($('c'),meta0);if(r){$('status').textContent+='\nrenderer: WebGPU';show('format-renderer','WebGPU');return r}}catch(e){console.warn(e)}$('status').textContent+='\nrenderer: Canvas2D fallback';show('format-renderer','Canvas2D');return new CanvasRenderer($('c'),meta0)}
function scheduleAudio(a,when){if(!ctxAudio)ctxAudio=new AudioContext();let frames=a.pcm.length/a.ch,b=ctxAudio.createBuffer(a.ch,frames,a.rate);for(let c=0;c<a.ch;c++){let x=b.getChannelData(c);for(let i=0;i<frames;i++)x[i]=a.pcm[i*a.ch+c]/32768}let s=ctxAudio.createBufferSource();s.buffer=b;s.connect(ctxAudio.destination);s.start(when);return frames/a.rate}
async function epoch(n,token){let e=idx.epochs[n];show('playback-epoch',`${n+1} / ${idx.epochs.length}`);let b=await range(currentUrl,e.offset,e.offset+e.len-1);if(token!==playToken)return;let ps=packets(b);ex.avelune_reset();for(const p of ps){if(p.kind===3){let a=decodeAudio(p.payload);if(ctxAudio){nextAudio=Math.max(nextAudio,ctxAudio.currentTime+.04);nextAudio+=scheduleAudio(a,nextAudio)}}}let base=performance.now(),ep=e.pts;for(const p of ps){if(p.kind!==2)continue;let f={pts:p.pts,...decodeVideo(p.payload)},wait=Math.max(0,(f.pts-ep)/1000-(performance.now()-base));if(wait)await new Promise(r=>setTimeout(r,wait));if(token!==playToken)return;renderer.render(f);let current=(f.pts/1e6).toFixed(2)+'s';$('time').textContent=current;show('playback-time',current);$('seek').value=f.pts/1e6}return true}
async function playFrom(sec){let token=++playToken;ex.avelune_reset();if(!ctxAudio)ctxAudio=new AudioContext();await ctxAudio.resume();nextAudio=ctxAudio.currentTime+.05;let ei=Math.max(0,idx.epochs.findLastIndex(e=>e.pts/1e6<=sec));for(let i=ei;i<idx.epochs.length;i++){if(token!==playToken)return;await epoch(i,token)}}
$('load').onclick=async()=>{try{show('state-label','LOADING');await wasmInit();currentUrl=$('url').value;idx=await index(currentUrl);$('status').textContent=`streams=${idx.streams.length} epochs=${idx.epochs.length}\nfront bytes=${32+idx.front.length}`;show('container-streams',idx.streams.length);show('container-epochs',idx.epochs.length);show('container-front',`${32+idx.front.length} B`);let vs=idx.streams.find(s=>s.kind===1),as=idx.streams.find(s=>s.kind===2);show('format-video',vs?streamFormat(vs):'—');show('format-audio',as?streamFormat(as):'—');renderer=await chooseRenderer(vs?.meta0||0);$('status').textContent+=`\nvideo meta0=0x${(vs?.meta0||0).toString(16)}`;let end=Math.max(...idx.epochs.map(e=>(e.pts+e.duration)/1e6));$('seek').max=end;$('seek').disabled=false;$('play').disabled=false;show('state-label','READY');await playFrom(0)}catch(e){show('state-label','ERROR');$('status').textContent='ERROR '+e.stack}};
$('play').onclick=()=>playFrom(+$('seek').value);$('seek').onchange=()=>playFrom(+$('seek').value);
